all:
  children:
    development:
      hosts:
        127.0.0.1: {}
    ungrouped: {}
    webserver:
      children:
        lb_servers:
          hosts:
            10.0.2.15:
              ansible_user_id: bader
              ftp_port: 77
              httpd_port: 8080
            localhost:
              ansible_user_id: bader
              ftp_port: 77
              httpd_port: 8080
      hosts:
        192.168.122.1: {}
