---
# handlers file for firewall
- name: reload firewalld
  service:
          name: firewalld
          state: restarted
- name: restart firewalld
  service:
          name: firewalld
          state: reloaded

